import 'dart:math';

import 'package:flutter/material.dart';

import 'captcha_mask_painter.dart';

/// A captcha widget that displays distorted text with random mask lines.
///
/// Every character of [text] is painted with a random skew, and random colored
/// lines are drawn over the text. This makes the captcha hard for bots to read
/// while staying easy for humans.
///
/// The text is usually generated with [generateText]:
///
/// ```dart
/// CaptchaView(
///   text: CaptchaView.generateText(length: 6),
///   lineColors: CaptchaView.rainbowColors,
///   onTap: () => setState(() {
///     text = CaptchaView.generateText(length: 6);
///   }),
/// )
/// ```
class CaptchaView extends StatelessWidget {
  /// Creates a captcha widget.
  const CaptchaView({
    super.key,
    this.width = double.infinity,
    this.height = 40,
    this.backgroundColor = Colors.white,
    this.style = const TextStyle(fontSize: 18),
    this.text = '',
    this.lineColors,
    this.decoration,
    this.onTap,
    this.lineCount = 5,
  });

  /// The width of the captcha.
  ///
  /// Defaults to [double.infinity], which makes the captcha fill all of the
  /// available horizontal space.
  final double width;

  /// The height of the captcha.
  final double height;

  /// The background color of the captcha.
  ///
  /// This is only used when no [decoration] is provided. Defaults to
  /// [Colors.white].
  final Color backgroundColor;

  /// The style used to paint the characters of [text].
  final TextStyle style;

  /// The text to display, usually generated by [generateText].
  final String text;

  /// The colors used for the random mask lines.
  ///
  /// When `null` (the default), no mask lines are drawn.
  final List<Color>? lineColors;

  /// The decoration of the captcha container.
  ///
  /// When provided, it replaces the default [BoxDecoration] that is built
  /// from [backgroundColor].
  final BoxDecoration? decoration;

  /// Called when the captcha view is tapped.
  ///
  /// Usually used to trigger a captcha text refresh.
  final VoidCallback? onTap;

  /// The number of noise mask lines to draw when [lineColors] is provided.
  final int lineCount;

  /// A list of rainbow colors that can be used as [lineColors].
  static const List<Color> rainbowColors = [
    Colors.red,
    Colors.orange,
    Colors.yellow,
    Colors.green,
    Colors.cyan,
    Colors.blue,
    Colors.purple,
  ];

  static final Random _random = Random();

  /// Similar/confusing characters that are excluded when `excludeSimilar = true`.
  static const String similarCharacters = '0Oo1Il';

  /// Generates a random text made of [length] characters.
  ///
  /// When [withNumber] is `true` (default), digits may appear in the output.
  /// When [withLetter] is `true` (default), letters may appear in the output.
  /// If [excludeSimilar] is `true`, easily confused characters (`0`, `O`, `o`,
  /// `1`, `I`, `l`) are omitted.
  /// Alternatively, [customAllowedCharacters] can be provided to specify the exact pool.
  static String generateText({
    int length = 4,
    bool withNumber = true,
    bool withLetter = true,
    bool excludeSimilar = false,
    String? customAllowedCharacters,
    Random? random,
  }) {
    assert(length > 0, 'length must be greater than 0');
    final rng = random ?? _random;

    if (customAllowedCharacters != null && customAllowedCharacters.isNotEmpty) {
      final pool = customAllowedCharacters;
      final out = StringBuffer();
      for (var i = 0; i < length; i++) {
        out.write(pool[rng.nextInt(pool.length)]);
      }
      return out.toString();
    }

    assert(
      withNumber || withLetter,
      'At least one of withNumber or withLetter must be true when customAllowedCharacters is not set.',
    );

    final charPool = <String>[];
    if (withNumber) {
      for (var i = 0; i <= 9; i++) {
        final char = i.toString();
        if (!excludeSimilar || !similarCharacters.contains(char)) {
          charPool.add(char);
        }
      }
    }

    if (withLetter) {
      // Uppercase A-Z (65-90)
      for (var code = 65; code <= 90; code++) {
        final char = String.fromCharCode(code);
        if (!excludeSimilar || !similarCharacters.contains(char)) {
          charPool.add(char);
        }
      }
      // Lowercase a-z (97-122)
      for (var code = 97; code <= 122; code++) {
        final char = String.fromCharCode(code);
        if (!excludeSimilar || !similarCharacters.contains(char)) {
          charPool.add(char);
        }
      }
    }

    if (charPool.isEmpty) {
      return '';
    }

    final out = StringBuffer();
    for (var i = 0; i < length; i++) {
      out.write(charPool[rng.nextInt(charPool.length)]);
    }
    return out.toString();
  }

  @override
  Widget build(BuildContext context) {
    final child = Container(
      width: width,
      height: height,
      clipBehavior: Clip.antiAlias,
      decoration: decoration ?? BoxDecoration(color: backgroundColor),
      child: Stack(
        alignment: AlignmentDirectional.center,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
            mainAxisSize: MainAxisSize.max,
            children: text.characters.map(_getText).toList(),
          ),
          CustomPaint(
            size: Size(width, height),
            painter: CaptchaMaskPainter(lineColors, lineCount: lineCount),
          ),
        ],
      ),
    );

    if (onTap != null) {
      return GestureDetector(
        onTap: onTap,
        behavior: HitTestBehavior.opaque,
        child: child,
      );
    }

    return child;
  }

  Widget _getText(String text) {
    final skewX = _random.nextInt(8).toDouble() / 10 * (_random.nextBool() ? -1 : 1);
    final skewY = _random.nextInt(8).toDouble() / 10 * (skewX > 0 ? -1 : 1);
    return Transform(
      transform: Matrix4.skew(skewX, skewY),
      child: Text(text, style: style),
    );
  }
}
